### ISSUE TITLE
Development team is set to "$(PROFILE_UUID)" instead of the specified development_team

### ISSUE THREAD

**Issue by skjalgsm** [Mindera/fastlane-plugin-cosigner#6]
The team is always set to the default value of "$(PROFILE_UUID)" instead of the specified development_team.

The issue is here:

`build_settings['DEVELOPMENT_TEAM'] = params[:development_team]`

then later on

      FastlaneCore::ConfigItem.new(key: :development_team,
                                         env_name: "TEAM_ID",
                                         description: "Development team identifier",
                                         default_value: "\"$(PROFILE_UUID)\""),

instead of using the DEVELOPMENT_TEAM id which is set, it is here trying to use the TEAM_ID. And when that does not work it tries to use the default value of "$(PROFILE_UUID)" (which also should have a better default value).

**Comment by p4checo** [comment]
Hi @Skjalgsm 

That parameter is configured to use:

-  the supplied value if given
- `env["TEAM_ID"]` if no value is supplied
- `"$(PROFILE_UUID)"` if no value is supplied nor the `env["TEAM_ID"]` is set

We use `TEAM_ID` env variable because that's what fastlane already uses for other tools, and the value should (typically) be the same. If you want another value you can simply supply it via parameter.

As for the `$(PROFILE_UUID)` default value, we realize that it probably makes no sense and we will remove it from a future release (as well as `$(PROFILE_NAME)` on `:profile_name` parameter). 

We will also change `:development_team` parameter to be optional so that if you don't provide any value or don't have any env var set, it'll simply be ignored.

I'll open up a PR shortly and you're free to provide your input.

Cheers! 🍻
